name: "Validate JSON"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate-json:
    name: "Validate JSON File"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify JSON File Exists
        id: verify-json
        run: |
          JSON_FILE_PATH="tools/json/config.temp.json"
          if [ -f "$JSON_FILE_PATH" ]; then
            echo "JSON file found at $JSON_FILE_PATH"
          else
            echo "Error: JSON file not found at $JSON_FILE_PATH"
            exit 1
          fi

      - name: Validate JSON Format
        id: validate-json
        run: |
          JSON_FILE_PATH="tools/json/config.temp.json"
          jq '.' $JSON_FILE_PATH > /dev/null
          if [ $? -eq 0 ]; then
            echo "JSON format is valid"
          else
            echo "Error: Invalid JSON format in $JSON_FILE_PATH"
            exit 1
          fi